export type {
  AppearancePreference,
  ConfirmBindEmailRequest,
  CurrentUser,
  DeleteCurrentUserRequest,
  DeleteCurrentUserResponse,
  LanguagePreference,
  RequestBindEmailCodeRequest,
  RequestBindEmailCodeResponse,
  UpdateCurrentUserAvatarResponse,
  UpdateCurrentUserProfileRequest,
  UpdateUserPreferencesRequest,
  UserOauthBinding,
  UserSettings,
} from '@haohaoxue/samepage-domain'
