export type {
  CreateDocumentRequest,
  CreateDocumentResponse,
  CreateDocumentSnapshotRequest,
  CreateDocumentSnapshotResponse,
  DocumentAsset,
  DocumentHead,
  DocumentRecent,
  DocumentSnapshot,
  DocumentTrashItem,
  DocumentTreeGroup,
  PatchDocumentMetaRequest,
  ResolveDocumentAssetsRequest,
  ResolveDocumentAssetsResponse,
  RestoreDocumentSnapshotRequest,
} from '@haohaoxue/samepage-domain'
